Sprint 04
MikeMolchanov/MovieQuiz pull request #1
Opened 2024-09-03 10:53 UTC by MikeMolchanov

Самостоятельная задача спринт 4

2024-09-03 13:48 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        show(quiz: questionStep)
Было бы хорошо сделать два разных метода, которые будут вызываться внутри `viewDidLoad`:
1) Код, который подготавливает на данном этапе вопрос
2) Код, который делает настройку UI, например, назвать отдельный метод `setupLayout()`

Такое разбиение позволит легче читать код, а также вносить последующие изменения

2024-09-03 13:49 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>      // MARK: - Lifecycle
До и после `MARK` стоит оставлять пустой отступ, это позволит легче видеть разделение кода

2024-09-03 13:50 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let givenAnswer = false // 2
Было бы хорошо убрать комментарии

2024-09-03 13:51 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Моделям по условию задания необходимо добавить `private`, чтобы они не были видны за пределами `MovieQuizViewController`

2024-09-03 13:51 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    // массив вопросов
Документирование кода – это важная и полезная практика, но лучше избегать комментариев, если их смысл уже выражен через название функции или переменной. Как писал Роберт Мартин, хороший код должен быть самодокументируемым, чтобы его было легко понять без лишних пояснений, но если это не получается, то хорошо было бы добавить комментарий. [Ссылка на статью про комментирование кода](https://habr.com/ru/companies/piter/articles/458990/)

2024-09-03 13:54 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            imageView.layer.cornerRadius = 6
Верстка не соответствует макетам фигмы в этих строчках кода. Стоит убрать рамку и поставить значение края как в макете

2024-09-03 13:57 UTC, Kirchberg requested changes
Привет, хорошая работа! В общем отзыве оставил пару критических комментариев, буду ждать исправлений :) Также добавил рекомендации, которые помогут улучшить проект ✨

2024-09-05 11:20 UTC, MikeMolchanov commented
Исправил основные замечания. Из рекомендаций исправил частично, т.к. отстаю от потока и пытаюсь догнать.

2024-09-05 11:55 UTC, Kirchberg approved these changes
Привет, больше никаких критических комментариев нет, молодец ✨

Approve ✅

2024-09-05 12:01 UTC, MikeMolchanov commented
Спасибо! Хорошего дня!

2024-10-26 10:33 UTC, merged